# Generated by Django 4.2.7 on 2023-12-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WayPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=19)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
