# Generated by Django 4.2.7 on 2023-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waypoint_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waypoint',
            name='country_name',
            field=models.CharField(default='unknown'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='port_name',
            field=models.CharField(default='unknown'),
        ),
        migrations.AddField(
            model_name='waypoint',
            name='region',
            field=models.CharField(default='unknown'),
        ),
    ]
