# Generated by Django 4.2.7 on 2023-12-05 22:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('underway_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='underway',
            name='crew',
        ),
        migrations.AddField(
            model_name='underway',
            name='manning',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('underway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='underway_app.underway')),
            ],
        ),
    ]
