# Generated by Django 4.2.7 on 2023-12-06 15:55

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import underway_app.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('underway_app', '0002_remove_underway_crew_underway_manning_crew'),
    ]

    operations = [
        migrations.AddField(
            model_name='underway',
            name='crew',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='underway',
            name='start_date',
            field=models.DateField(error_messages='invalid start date', validators=[underway_app.validators.validate_future_date, django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 6))]),
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
    ]
