# Generated by Django 4.2.7 on 2023-12-08 17:01

import datetime
import django.core.validators
from django.db import migrations, models
import underway_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('underway_app', '0004_underway_waypoints_alter_underway_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underway',
            name='start_date',
            field=models.DateField(error_messages='invalid start date', validators=[underway_app.validators.validate_future_date, django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 8))]),
        ),
    ]
