# Generated by Django 4.2.7 on 2023-12-13 15:46

import datetime
import django.core.validators
from django.db import migrations, models
import underway_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('underway_app', '0006_alter_underway_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underway',
            name='duration',
            field=models.IntegerField(error_messages='invalid duration', null=True),
        ),
        migrations.AlterField(
            model_name='underway',
            name='manning',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='underway',
            name='start_date',
            field=models.DateField(error_messages='invalid start date', validators=[underway_app.validators.validate_future_date, django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 13))]),
        ),
    ]
