# Generated by Django 4.2.7 on 2023-12-14 16:09

import datetime
import django.core.validators
from django.db import migrations, models
import underway_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('underway_app', '0007_alter_underway_duration_alter_underway_manning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='underway',
            name='start_date',
            field=models.DateField(error_messages='invalid start date', validators=[underway_app.validators.validate_future_date, django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 12, 14))]),
        ),
    ]
