# Generated by Django 4.2.7 on 2023-12-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.CharField(default='swabbie'),
        ),
    ]
